name: Lighthouse-CI
on:
  pull_request:
    branches:
      - 'main'
      - 'release'
  push:
    branches:
      - 'main'
      - 'release'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.13.0
      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: |
            ./node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: npm install -g yarn
      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile --check-files
      - run: yarn build
      - name: upload dist artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-artifacts
          path: |
            dist
  lhci:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: restore-build
        with:
          path: |
            ./node_modules
          key: ${{ runner.os }}-yarn-
      - name: download dist artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-artifacts
      - run: |
          npm install -g @lhci/cli@0.9.0
          lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
